services:
  web:
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "127.0.0.1:8050:8000"
    volumes:
      - ./deploy-data/staticfiles:/app/staticfiles
      - ./deploy-data/media:/app/media
      - ./deploy-data/data:/app/data
    restart: unless-stopped