# Generated by Django 5.2.13 on 2026-04-26 15:00

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EditablePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("title_es", models.CharField(max_length=255, null=True)),
                ("title_eu", models.CharField(max_length=255, null=True)),
                ("title_fr", models.CharField(max_length=255, null=True)),
                ("title_en", models.CharField(max_length=255, null=True)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("summary", models.TextField(blank=True)),
                ("summary_es", models.TextField(blank=True, null=True)),
                ("summary_eu", models.TextField(blank=True, null=True)),
                ("summary_fr", models.TextField(blank=True, null=True)),
                ("summary_en", models.TextField(blank=True, null=True)),
                ("content", tinymce.models.HTMLField(blank=True)),
                ("content_es", tinymce.models.HTMLField(blank=True, null=True)),
                ("content_eu", tinymce.models.HTMLField(blank=True, null=True)),
                ("content_fr", tinymce.models.HTMLField(blank=True, null=True)),
                ("content_en", tinymce.models.HTMLField(blank=True, null=True)),
                (
                    "featured_image",
                    models.ImageField(blank=True, null=True, upload_to="pages/"),
                ),
                ("menu_group", models.CharField(blank=True, max_length=100)),
                (
                    "menu_group_es",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "menu_group_eu",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "menu_group_fr",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "menu_group_en",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("seo_title", models.CharField(blank=True, max_length=255)),
                (
                    "seo_title_es",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "seo_title_eu",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "seo_title_fr",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "seo_title_en",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("seo_description", models.TextField(blank=True)),
                ("seo_description_es", models.TextField(blank=True, null=True)),
                ("seo_description_eu", models.TextField(blank=True, null=True)),
                ("seo_description_fr", models.TextField(blank=True, null=True)),
                ("seo_description_en", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="pages.editablepage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Editable page",
                "verbose_name_plural": "Editable pages",
                "ordering": ("order", "title"),
            },
        ),
    ]
