# Generated by Django 5.2.13 on 2026-04-26 15:00

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=255)),
                ("question_es", models.CharField(max_length=255, null=True)),
                ("question_eu", models.CharField(max_length=255, null=True)),
                ("question_fr", models.CharField(max_length=255, null=True)),
                ("question_en", models.CharField(max_length=255, null=True)),
                ("answer", tinymce.models.HTMLField()),
                ("answer_es", tinymce.models.HTMLField(null=True)),
                ("answer_eu", tinymce.models.HTMLField(null=True)),
                ("answer_fr", tinymce.models.HTMLField(null=True)),
                ("answer_en", tinymce.models.HTMLField(null=True)),
                ("category", models.CharField(blank=True, max_length=120)),
                (
                    "category_es",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "category_eu",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "category_fr",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "category_en",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("show_on_home", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQs",
                "ordering": ("order", "id"),
            },
        ),
    ]
