# Generated by Django 5.2.13 on 2026-04-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HomeContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hero_title", models.CharField(blank=True, max_length=255)),
                (
                    "hero_title_es",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "hero_title_eu",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "hero_title_fr",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "hero_title_en",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("hero_subtitle", models.CharField(blank=True, max_length=255)),
                (
                    "hero_subtitle_es",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "hero_subtitle_eu",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "hero_subtitle_fr",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "hero_subtitle_en",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("hero_text", models.TextField(blank=True)),
                ("hero_text_es", models.TextField(blank=True, null=True)),
                ("hero_text_eu", models.TextField(blank=True, null=True)),
                ("hero_text_fr", models.TextField(blank=True, null=True)),
                ("hero_text_en", models.TextField(blank=True, null=True)),
                (
                    "hero_image",
                    models.ImageField(blank=True, null=True, upload_to="home/"),
                ),
                ("intro_title", models.CharField(blank=True, max_length=255)),
                (
                    "intro_title_es",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "intro_title_eu",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "intro_title_fr",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "intro_title_en",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("intro_text", models.TextField(blank=True)),
                ("intro_text_es", models.TextField(blank=True, null=True)),
                ("intro_text_eu", models.TextField(blank=True, null=True)),
                ("intro_text_fr", models.TextField(blank=True, null=True)),
                ("intro_text_en", models.TextField(blank=True, null=True)),
                ("process_title", models.CharField(blank=True, max_length=255)),
                (
                    "process_title_es",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "process_title_eu",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "process_title_fr",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "process_title_en",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("process_text", models.TextField(blank=True)),
                ("process_text_es", models.TextField(blank=True, null=True)),
                ("process_text_eu", models.TextField(blank=True, null=True)),
                ("process_text_fr", models.TextField(blank=True, null=True)),
                ("process_text_en", models.TextField(blank=True, null=True)),
                (
                    "process_image",
                    models.ImageField(blank=True, null=True, upload_to="home/"),
                ),
                ("services_title", models.CharField(blank=True, max_length=255)),
                (
                    "services_title_es",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "services_title_eu",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "services_title_fr",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "services_title_en",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("services_text", models.TextField(blank=True)),
                ("services_text_es", models.TextField(blank=True, null=True)),
                ("services_text_eu", models.TextField(blank=True, null=True)),
                ("services_text_fr", models.TextField(blank=True, null=True)),
                ("services_text_en", models.TextField(blank=True, null=True)),
                ("team_title", models.CharField(blank=True, max_length=255)),
                (
                    "team_title_es",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "team_title_eu",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "team_title_fr",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "team_title_en",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("team_text", models.TextField(blank=True)),
                ("team_text_es", models.TextField(blank=True, null=True)),
                ("team_text_eu", models.TextField(blank=True, null=True)),
                ("team_text_fr", models.TextField(blank=True, null=True)),
                ("team_text_en", models.TextField(blank=True, null=True)),
                ("faq_title", models.CharField(blank=True, max_length=255)),
                (
                    "faq_title_es",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "faq_title_eu",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "faq_title_fr",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "faq_title_en",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("faq_text", models.TextField(blank=True)),
                ("faq_text_es", models.TextField(blank=True, null=True)),
                ("faq_text_eu", models.TextField(blank=True, null=True)),
                ("faq_text_fr", models.TextField(blank=True, null=True)),
                ("faq_text_en", models.TextField(blank=True, null=True)),
                ("contact_title", models.CharField(blank=True, max_length=255)),
                (
                    "contact_title_es",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "contact_title_eu",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "contact_title_fr",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "contact_title_en",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("contact_text", models.TextField(blank=True)),
                ("contact_text_es", models.TextField(blank=True, null=True)),
                ("contact_text_eu", models.TextField(blank=True, null=True)),
                ("contact_text_fr", models.TextField(blank=True, null=True)),
                ("contact_text_en", models.TextField(blank=True, null=True)),
                ("seo_title", models.CharField(blank=True, max_length=255)),
                (
                    "seo_title_es",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "seo_title_eu",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "seo_title_fr",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "seo_title_en",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("seo_description", models.TextField(blank=True)),
                ("seo_description_es", models.TextField(blank=True, null=True)),
                ("seo_description_eu", models.TextField(blank=True, null=True)),
                ("seo_description_fr", models.TextField(blank=True, null=True)),
                ("seo_description_en", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Home content",
                "verbose_name_plural": "Home content",
            },
        ),
    ]
