# Generated by Django 5.2.13 on 2026-04-26 15:00

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Collaborator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("name_es", models.CharField(max_length=255, null=True)),
                ("name_eu", models.CharField(max_length=255, null=True)),
                ("name_fr", models.CharField(max_length=255, null=True)),
                ("name_en", models.CharField(max_length=255, null=True)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                (
                    "collaborator_type",
                    models.CharField(
                        choices=[("person", "Person"), ("entity", "Entity")],
                        default="person",
                        max_length=20,
                    ),
                ),
                (
                    "membership_type",
                    models.CharField(
                        choices=[
                            ("own_member", "Own member"),
                            ("external_member", "External member"),
                        ],
                        default="own_member",
                        max_length=20,
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=255)),
                ("role_es", models.CharField(blank=True, max_length=255, null=True)),
                ("role_eu", models.CharField(blank=True, max_length=255, null=True)),
                ("role_fr", models.CharField(blank=True, max_length=255, null=True)),
                ("role_en", models.CharField(blank=True, max_length=255, null=True)),
                ("photo", models.ImageField(blank=True, null=True, upload_to="team/")),
                ("short_description", models.TextField(blank=True)),
                ("short_description_es", models.TextField(blank=True, null=True)),
                ("short_description_eu", models.TextField(blank=True, null=True)),
                ("short_description_fr", models.TextField(blank=True, null=True)),
                ("short_description_en", models.TextField(blank=True, null=True)),
                ("full_description", tinymce.models.HTMLField(blank=True)),
                (
                    "full_description_es",
                    tinymce.models.HTMLField(blank=True, null=True),
                ),
                (
                    "full_description_eu",
                    tinymce.models.HTMLField(blank=True, null=True),
                ),
                (
                    "full_description_fr",
                    tinymce.models.HTMLField(blank=True, null=True),
                ),
                (
                    "full_description_en",
                    tinymce.models.HTMLField(blank=True, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=100)),
                ("website_url", models.URLField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
                ("instagram_url", models.URLField(blank=True)),
                ("facebook_url", models.URLField(blank=True)),
                ("x_url", models.URLField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Collaborator",
                "verbose_name_plural": "Collaborators",
                "ordering": ("order", "name"),
            },
        ),
    ]
